// Data

const skills = [
  {
    icon: "images/java.svg",
    name: "Java"
  },
  {
    icon: "images/javascript.svg",
    name: "JavaScript"
  },
  {
    icon: "images/typescript.svg",
    name: "TypeScript"
  },
  {
    icon: "images/css.svg",
    name: "CSS"
  },
  {
    icon: "images/express.svg",
    name: "ExpressJS"
  }, {
    icon: "images/html.svg",
    name: "HTML"
  },
  {
    icon: "images/mui.svg",
    name: "MaterialUI"
  },
  {
    icon: "images/nextjs.svg",
    name: "NextJS"
  }, {
    icon: "images/nodejs.svg",
    name: "NodeJS"
  },
  {
    icon: "images/sass.svg",
    name: "Sass"
  },
  {
    icon: "images/react.svg",
    name: "React"
  },

  {
    icon: "images/mongodb.svg",
    name: "MongoDB"
  },
]

const experiences = [
  {
    companyName: "Zeus Learning",
    role: "Software Developer",
    duration: "June 2023 - Present",
    description: [
      "Worked on their assessment platform.",
      "Worked with HTML canvas to enable students to draw their response.",
      "Extended fabricJS Textbox to implement functionality like word break and text scroll on overflow.",
    ]
  },
  {
    companyName: "Exam Lounge",
    role: "Frontend Developer",
    duration: "June 2021 - July 2022",
    description: [
      "Worked on improving the educator's user experience and increasing their productivity.",
      "Created a full-featured WYSIWYG rich text editor. It enabled microsoft word like table insertion, drag/drop upload for images, insertion of sanitized html in raw form or as editable text content, internal linking for blogs.",
      "Made sure the editor was backwards compatible, by creating a custom parser to convert the data generated by the previous wysiwyg text editor.",
      "Added issue resolving capabilities to their website. Where an educator could see all the opened issues for the questions he/she has created and swiftly resolve the same."
    ]
  }
]

const projects=[]

// Elements
const navbar = document.getElementById("navbar");
const heroSection = document.getElementById('hero');
const skillsContainer = document.getElementById('skills');
const experiencesContainer = document.getElementById("experiences")
heroSection.style.height = `${window.innerHeight - navbar.offsetHeight}px`;

skills.forEach(skill => {
  const skillHtml = `<span class="flex gap-4 items-center">
                        <img class="w-10 " src=${skill.icon} alt="" />
                        <span>${skill.name}</span>
                     </span>`
  skillsContainer.insertAdjacentHTML('beforeend', skillHtml)
})

experiences.forEach(experience => {
  const { companyName, role, duration, description } = experience;
  const jobExperienceContainer = document.createElement("div");
  jobExperienceContainer.classList.add("text-black","flex","flex-col", "gap-3")

  const experienceHtml = `<h1 class="text-2xl">${role}</h1>
                          <p class="text-teal-400">${companyName}</p>
                          <span class="text-sm">${duration}</span>
                          <ul class="list-inside list-disc">
                          </ul>`
  jobExperienceContainer.innerHTML = experienceHtml
  experiencesContainer.insertAdjacentElement("beforeend",jobExperienceContainer)
  const list = jobExperienceContainer.querySelector("ul");

  description.forEach(line => list.insertAdjacentHTML("beforeend", `<li>${line}</li>`))

})